# Jekyll configuration
title: yunus ~ blog
description: ''
name: yunus ~ blog

# url is currently only used only for the RSS feed in feed.xml
url: http://oksuz.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'oksuz'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-74987136-1'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'yunusblog'
comments: true

permalink: /:categories/:title/
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

include: [".htaccess"]
exclude: ["deployer.py", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]